### ISSUE TITLE
Mouse Wheel

### ISSUE THREAD

**Issue by brunosimis** [tomzx/gkm#8]
In "JNativeHook.jar" demo on Gkm's directory we can view mouse wheel's data, but even listen to every events on Gkm's module ( gkm.events.onAny(function(data) {console.log(this.event+' '+data);}); ) there is no mouse wheel's data =(. I checked gkm-java source and look to me that there is no emitter to JNativeHooks's "NativeMouseWheelListener", I don't know plenty Java and can be completely wrong. 
Is this data available on Gkm.js? How can I help develop this functionality if there isn't? 
Thank you for this package, It's the only one that satisfy my needs on Windows 10, and I realy want to only depends on it! English is not my mother tongue; please excuse any errors on my part =).

**Comment by tomzx** [comment]
Hi @brunosimis,

Please try v0.2.0. I've added mouse wheel scrolling events to it.

**Comment by brunosimis** [comment]
Hi @tomzx, I replaced 'gkm.jar' and it's perfect now! Thank you!
